name: Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5.x'
    - name: Build with dependencies
      run: |
        gem install bundler -v 1.17
        bundle install
    - name: Test with rspec
      run: |
        bundle exec rspec spec/
    - name: Lint with rubocop
      run: |
        bundle exec rubocop
